<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-0H005IDA" name="com.qa.hap.tests.LoginPageTest" tests="3" failures="1" timestamp="4 Jul 2022 03:15:03 GMT" time="0.314" errors="0">
  <testcase name="isForgotPwdLinkExistTest" time="0.099" classname="com.qa.hap.tests.LoginPageTest"/>
  <testcase name="loginPageTitleTest" time="0.178" classname="com.qa.hap.tests.LoginPageTest"/>
  <testcase name="getLoginPageUrl" time="0.037" classname="com.qa.hap.tests.LoginPageTest">
    <failure type="java.lang.AssertionError" message="expected [helius_testing_hapteam/login.html] but found [https://hap-testing.heliusapp.com/helius_testing_hapteam/login.html]">
      <![CDATA[java.lang.AssertionError: expected [helius_testing_hapteam/login.html] but found [https://hap-testing.heliusapp.com/helius_testing_hapteam/login.html]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.qa.hap.tests.LoginPageTest.getLoginPageUrl(LoginPageTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- getLoginPageUrl -->
</testsuite> <!-- com.qa.hap.tests.LoginPageTest -->
